package:
  name: ros
  version: 2020.03.26

source:
  - git_url: https://github.com/ros-gbp/resource_retriever-release.git
    git_rev: release/noetic/resource_retriever/1.12.6-1
    folder: ros-noetic-resource-retriever/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-resource-retriever
    version: 1.12.6
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - libcurl
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-rosconsole
        - ros-noetic-roslib
      run:
        - boost
        - libcurl
        - python {{ python }}
        - ros-noetic-rosconsole
        - ros-noetic-roslib
        - rospkg
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
