package:
  name: ros
  version: 2020.04.01

source:
  - git_url: https://github.com/ros-gbp/diagnostics-release.git
    git_rev: release/noetic/self_test/1.9.4-1
    folder: ros-noetic-self-test/src/work
  - git_url: https://github.com/ros-gbp/diagnostics-release.git
    git_rev: release/noetic/diagnostics/1.9.4-1
    folder: ros-noetic-diagnostics/src/work
  - git_url: https://github.com/ros-gbp/bond_core-release.git
    git_rev: release/noetic/bondpy/1.8.4-1
    folder: ros-noetic-bondpy/src/work
  - git_url: https://github.com/ros-gbp/diagnostics-release.git
    git_rev: release/noetic/diagnostic_aggregator/1.9.4-1
    folder: ros-noetic-diagnostic-aggregator/src/work
  - git_url: https://github.com/ros-gbp/urdfdom_py-release.git
    git_rev: release/noetic/urdfdom_py/0.4.3-1
    folder: ros-noetic-urdfdom-py/src/work
  - git_url: https://github.com/ros-gbp/diagnostics-release.git
    git_rev: release/noetic/diagnostic_updater/1.9.4-1
    folder: ros-noetic-diagnostic-updater/src/work
  - git_url: https://github.com/ros-gbp/diagnostics-release.git
    git_rev: release/noetic/diagnostic_common_diagnostics/1.9.4-1
    folder: ros-noetic-diagnostic-common-diagnostics/src/work
  - git_url: https://github.com/ros-gbp/diagnostics-release.git
    git_rev: release/noetic/diagnostic_analysis/1.9.4-1
    folder: ros-noetic-diagnostic-analysis/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-self-test
    version: 1.9.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-diagnostic-msgs
        - ros-noetic-diagnostic-updater
        - ros-noetic-roscpp
        - ros-noetic-rostest
      run:
        - python {{ python }}
        - ros-noetic-diagnostic-msgs
        - ros-noetic-diagnostic-updater
        - ros-noetic-roscpp
    script: bld_catkin.bat
  - name: ros-noetic-diagnostics
    version: 1.9.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-diagnostic-aggregator
        - ros-noetic-diagnostic-analysis
        - ros-noetic-diagnostic-common-diagnostics
        - ros-noetic-diagnostic-updater
        - ros-noetic-self-test
      run:
        - python {{ python }}
        - ros-noetic-diagnostic-aggregator
        - ros-noetic-diagnostic-analysis
        - ros-noetic-diagnostic-common-diagnostics
        - ros-noetic-diagnostic-updater
        - ros-noetic-self-test
    script: bld_catkin.bat
  - name: ros-noetic-bondpy
    version: 1.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-bond
        - ros-noetic-catkin
        - ros-noetic-rospy
        - ros-noetic-smclib
      run:
        - python {{ python }}
        - ros-noetic-rospy
        - ros-noetic-smclib
    script: bld_catkin.bat
  - name: ros-noetic-diagnostic-aggregator
    version: 1.9.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-bondcpp
        - ros-noetic-bondpy
        - ros-noetic-catkin
        - ros-noetic-diagnostic-msgs
        - ros-noetic-pluginlib
        - ros-noetic-roscpp
        - ros-noetic-rospy
        - ros-noetic-rostest
        - ros-noetic-xmlrpcpp
      run:
        - python {{ python }}
        - ros-noetic-bondcpp
        - ros-noetic-bondpy
        - ros-noetic-diagnostic-msgs
        - ros-noetic-pluginlib
        - ros-noetic-roscpp
        - ros-noetic-rospy
        - ros-noetic-xmlrpcpp
    script: bld_catkin.bat
  - name: ros-noetic-urdfdom-py
    version: 0.4.3
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - mock
        - python {{ python }}
        - ros-noetic-catkin
        - setuptools
      run:
        - python {{ python }}
        - pyyaml
        - ros-noetic-rospy
    script: bld_catkin.bat
  - name: ros-noetic-diagnostic-updater
    version: 1.9.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-diagnostic-msgs
        - ros-noetic-roscpp
        - ros-noetic-rostest
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-diagnostic-msgs
        - ros-noetic-roscpp
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-diagnostic-common-diagnostics
    version: 1.9.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - psutil
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-diagnostic-updater
        - ros-noetic-rospy
        - ros-noetic-rostest
        - ros-noetic-tf
      run:
        - psutil
        - python {{ python }}
        - ros-noetic-diagnostic-updater
        - ros-noetic-rospy
        - ros-noetic-tf
    script: bld_catkin.bat
  - name: ros-noetic-diagnostic-analysis
    version: 1.9.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-diagnostic-msgs
        - ros-noetic-rosbag
        - ros-noetic-roslib
        - ros-noetic-rostest
      run:
        - python {{ python }}
        - ros-noetic-diagnostic-msgs
        - ros-noetic-rosbag
        - ros-noetic-roslib
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
