package:
  name: ros
  version: 2020.04.26

source:
  - git_url: https://github.com/ros-gbp/media_export-release.git
    git_rev: release/noetic/media_export/0.3.0-1
    folder: ros-noetic-media-export/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-media-export
    version: 0.3.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge
