package:
  name: ros
  version: 2020.03.30

source:
  - git_url: https://github.com/ros-gbp/xacro-release.git
    git_rev: release/noetic/xacro/1.14.1-1
    folder: ros-noetic-xacro/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-xacro
    version: 1.14.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-roslaunch
        - ros-noetic-roslint
        - ros-noetic-rostest
      run:
        - python {{ python }}
        - ros-noetic-roslaunch
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
