package:
  name: ros
  version: 2020.03.27

source:
  - git_url: https://github.com/roboception-gbp/rc_common_msgs-release.git
    git_rev: release/noetic/rc_common_msgs/0.4.1-1
    folder: ros-noetic-rc-common-msgs/src/work
  - git_url: https://github.com/ros-gbp/octomap-release.git
    git_rev: release/noetic/octomap/1.9.5-1
    folder: ros-noetic-octomap/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-rc-common-msgs
    version: 0.4.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-octomap
    version: 1.9.5
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - cmake
        - python {{ python }}
      run:
        - python {{ python }}
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
