package:
  name: ros
  version: 2020.04.26

source:
  - git_url: https://github.com/ros-gbp/interactive_markers-release.git
    git_rev: release/noetic/interactive_markers/1.12.0-1
    folder: ros-noetic-interactive-markers/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-interactive-markers
    version: 1.12.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-rospy
        - ros-noetic-rostest
        - ros-noetic-std-msgs
        - ros-noetic-tf2-geometry-msgs
        - ros-noetic-tf2-ros
        - ros-noetic-visualization-msgs
      run:
        - python {{ python }}
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-rospy
        - ros-noetic-rostest
        - ros-noetic-std-msgs
        - ros-noetic-tf2-geometry-msgs
        - ros-noetic-tf2-ros
        - ros-noetic-visualization-msgs
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge
