package:
  name: ros
  version: 2020.04.05

source:
  - git_url: https://github.com/ros-gbp/bond_core-release.git
    git_rev: release/noetic/bond_core/1.8.4-1
    folder: ros-noetic-bond-core/src/work
  - git_url: https://github.com/ros-gbp/nodelet_core-release.git
    git_rev: release/noetic/nodelet_core/1.10.0-1
    folder: ros-noetic-nodelet-core/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-bond-core
    version: 1.8.4
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
        - ros-noetic-bond
        - ros-noetic-bondcpp
        - ros-noetic-bondpy
        - ros-noetic-smclib
    script: bld_catkin.bat
  - name: ros-noetic-nodelet-core
    version: 1.10.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
        - ros-noetic-nodelet
        - ros-noetic-nodelet-topic-tools
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge
