package:
  name: ros
  version: 2020.03.26

source:
  - git_url: https://github.com/ros-gbp/geometry_angles_utils-release.git
    git_rev: release/noetic/angles/1.9.13-1
    folder: ros-noetic-angles/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-angles
    version: 1.9.13
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-rosunit
      run:
        - python {{ python }}
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
