package:
  name: ros
  version: 2020.03.25

source:
  - git_url: https://github.com/ros-gbp/rosbag_migration_rule-release.git
    git_rev: release/noetic/rosbag_migration_rule/1.0.1-1
    folder: ros-noetic-rosbag-migration-rule/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/common_msgs/1.12.7-1
    folder: ros-noetic-common-msgs/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/stereo_msgs/1.12.7-1
    folder: ros-noetic-stereo-msgs/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/nav_msgs/1.12.7-1
    folder: ros-noetic-nav-msgs/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/trajectory_msgs/1.12.7-1
    folder: ros-noetic-trajectory-msgs/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/visualization_msgs/1.12.7-1
    folder: ros-noetic-visualization-msgs/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/diagnostic_msgs/1.12.7-1
    folder: ros-noetic-diagnostic-msgs/src/work
  - git_url: https://github.com/ros-gbp/common_msgs-release.git
    git_rev: release/noetic/shape_msgs/1.12.7-1
    folder: ros-noetic-shape-msgs/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-rosbag-migration-rule
    version: 1.0.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
    script: bld_catkin.bat
  - name: ros-noetic-common-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-actionlib-msgs
        - ros-noetic-catkin
        - ros-noetic-diagnostic-msgs
        - ros-noetic-geometry-msgs
        - ros-noetic-nav-msgs
        - ros-noetic-sensor-msgs
        - ros-noetic-shape-msgs
        - ros-noetic-stereo-msgs
        - ros-noetic-trajectory-msgs
        - ros-noetic-visualization-msgs
      run:
        - python {{ python }}
        - ros-noetic-actionlib-msgs
        - ros-noetic-diagnostic-msgs
        - ros-noetic-geometry-msgs
        - ros-noetic-nav-msgs
        - ros-noetic-sensor-msgs
        - ros-noetic-shape-msgs
        - ros-noetic-stereo-msgs
        - ros-noetic-trajectory-msgs
        - ros-noetic-visualization-msgs
    script: bld_catkin.bat
  - name: ros-noetic-stereo-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-sensor-msgs
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-sensor-msgs
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-nav-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-actionlib-msgs
        - ros-noetic-catkin
        - ros-noetic-geometry-msgs
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-actionlib-msgs
        - ros-noetic-geometry-msgs
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-trajectory-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-geometry-msgs
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-rosbag-migration-rule
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-geometry-msgs
        - ros-noetic-message-runtime
        - ros-noetic-rosbag-migration-rule
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-visualization-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-geometry-msgs
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-geometry-msgs
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-diagnostic-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-shape-msgs
    version: 1.12.7
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-geometry-msgs
        - ros-noetic-message-generation
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-geometry-msgs
        - ros-noetic-message-runtime
        - ros-noetic-std-msgs
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
