package:
  name: ros
  version: 2020.03.26

source:
  - git_url: https://github.com/ros-gbp/laser_geometry-release.git
    git_rev: release/noetic/laser_geometry/1.6.5-1
    folder: ros-noetic-laser-geometry/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-laser-geometry
    version: 1.6.5
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - eigen
        - python {{ python }}
        - ros-noetic-angles
        - ros-noetic-catkin
        - ros-noetic-roscpp
        - ros-noetic-rosunit
        - ros-noetic-sensor-msgs
        - ros-noetic-tf
        - ros-noetic-tf2
      run:
        - boost
        - eigen
        - numpy
        - python {{ python }}
        - ros-noetic-angles
        - ros-noetic-roscpp
        - ros-noetic-sensor-msgs
        - ros-noetic-tf
        - ros-noetic-tf2
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
