package:
  name: ros
  version: 2020.04.27

source:
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/ackermann_steering_controller/0.16.1-1
    folder: ros-noetic-ackermann-steering-controller/src/work
  - git_url: https://github.com/mikeferguson/code_coverage-gbp.git
    git_rev: release/noetic/code_coverage/0.4.1-1
    folder: ros-noetic-code-coverage/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/diff_drive_controller/0.16.1-1
    folder: ros-noetic-diff-drive-controller/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/effort_controllers/0.16.1-1
    folder: ros-noetic-effort-controllers/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/force_torque_sensor_controller/0.16.1-1
    folder: ros-noetic-force-torque-sensor-controller/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/forward_command_controller/0.16.1-1
    folder: ros-noetic-forward-command-controller/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/gripper_action_controller/0.16.1-1
    folder: ros-noetic-gripper-action-controller/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/imu_sensor_controller/0.16.1-1
    folder: ros-noetic-imu-sensor-controller/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/joint_state_controller/0.16.1-1
    folder: ros-noetic-joint-state-controller/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/joint_trajectory_controller/0.16.1-1
    folder: ros-noetic-joint-trajectory-controller/src/work
  - git_url: https://github.com/ros-gbp/kdl_parser-release.git
    git_rev: release/noetic/kdl_parser/1.14.0-1
    folder: ros-noetic-kdl-parser/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/position_controllers/0.16.1-1
    folder: ros-noetic-position-controllers/src/work
  - git_url: https://github.com/ros-gbp/robot_state_publisher-release.git
    git_rev: release/noetic/robot_state_publisher/1.15.0-1
    folder: ros-noetic-robot-state-publisher/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/ros_controllers/0.16.1-1
    folder: ros-noetic-ros-controllers/src/work
  - git_url: https://github.com/ros-gbp/ros_controllers-release.git
    git_rev: release/noetic/velocity_controllers/0.16.1-1
    folder: ros-noetic-velocity-controllers/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-ackermann-steering-controller
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - boost
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-controller-interface
        - ros-noetic-controller-manager
        - ros-noetic-diff-drive-controller
        - ros-noetic-geometry-msgs
        - ros-noetic-hardware-interface
        - ros-noetic-nav-msgs
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-rostest
        - ros-noetic-rosunit
        - ros-noetic-std-msgs
        - ros-noetic-std-srvs
        - ros-noetic-tf
        - ros-noetic-urdf
        - ros-noetic-xacro
      run:
        - boost
        - python {{ python }}
        - ros-noetic-controller-interface
        - ros-noetic-diff-drive-controller
        - ros-noetic-hardware-interface
        - ros-noetic-nav-msgs
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-tf
        - ros-noetic-urdf
    script: bld_catkin.bat
  - name: ros-noetic-code-coverage
    version: 0.4.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - coverage
        - lcov
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - coverage
        - lcov
        - python {{ python }}
    script: bld_catkin.bat
  - name: ros-noetic-diff-drive-controller
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-control-msgs
        - ros-noetic-controller-interface
        - ros-noetic-controller-manager
        - ros-noetic-dynamic-reconfigure
        - ros-noetic-nav-msgs
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-rosgraph-msgs
        - ros-noetic-rostest
        - ros-noetic-std-srvs
        - ros-noetic-tf
        - ros-noetic-urdf
        - ros-noetic-xacro
      run:
        - python {{ python }}
        - ros-noetic-control-msgs
        - ros-noetic-controller-interface
        - ros-noetic-dynamic-reconfigure
        - ros-noetic-nav-msgs
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-tf
        - ros-noetic-urdf
    script: bld_catkin.bat
  - name: ros-noetic-effort-controllers
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-angles
        - ros-noetic-catkin
        - ros-noetic-control-msgs
        - ros-noetic-control-toolbox
        - ros-noetic-controller-interface
        - ros-noetic-controller-manager
        - ros-noetic-forward-command-controller
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-robot-state-publisher
        - ros-noetic-rosgraph-msgs
        - ros-noetic-rostest
        - ros-noetic-sensor-msgs
        - ros-noetic-std-msgs
        - ros-noetic-urdf
        - ros-noetic-xacro
      run:
        - python {{ python }}
        - ros-noetic-angles
        - ros-noetic-control-msgs
        - ros-noetic-control-toolbox
        - ros-noetic-controller-interface
        - ros-noetic-forward-command-controller
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-urdf
    script: bld_catkin.bat
  - name: ros-noetic-force-torque-sensor-controller
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-controller-interface
        - ros-noetic-geometry-msgs
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
      run:
        - python {{ python }}
        - ros-noetic-controller-interface
        - ros-noetic-geometry-msgs
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
    script: bld_catkin.bat
  - name: ros-noetic-forward-command-controller
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-controller-interface
        - ros-noetic-hardware-interface
        - ros-noetic-realtime-tools
        - ros-noetic-std-msgs
      run:
        - python {{ python }}
        - ros-noetic-controller-interface
        - ros-noetic-hardware-interface
        - ros-noetic-realtime-tools
        - ros-noetic-std-msgs
    script: bld_catkin.bat
  - name: ros-noetic-gripper-action-controller
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-actionlib
        - ros-noetic-angles
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - ros-noetic-control-msgs
        - ros-noetic-control-toolbox
        - ros-noetic-controller-interface
        - ros-noetic-controller-manager
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-trajectory-msgs
        - ros-noetic-urdf
        - ros-noetic-xacro
      run:
        - python {{ python }}
        - ros-noetic-actionlib
        - ros-noetic-angles
        - ros-noetic-cmake-modules
        - ros-noetic-control-msgs
        - ros-noetic-control-toolbox
        - ros-noetic-controller-interface
        - ros-noetic-controller-manager
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-trajectory-msgs
        - ros-noetic-urdf
        - ros-noetic-xacro
    script: bld_catkin.bat
  - name: ros-noetic-imu-sensor-controller
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-controller-interface
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-sensor-msgs
      run:
        - python {{ python }}
        - ros-noetic-controller-interface
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-sensor-msgs
    script: bld_catkin.bat
  - name: ros-noetic-joint-state-controller
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-controller-interface
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-rostest
        - ros-noetic-sensor-msgs
      run:
        - python {{ python }}
        - ros-noetic-controller-interface
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-sensor-msgs
    script: bld_catkin.bat
  - name: ros-noetic-joint-trajectory-controller
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-actionlib
        - ros-noetic-angles
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - ros-noetic-code-coverage
        - ros-noetic-control-msgs
        - ros-noetic-control-toolbox
        - ros-noetic-controller-interface
        - ros-noetic-controller-manager
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-rostest
        - ros-noetic-trajectory-msgs
        - ros-noetic-urdf
        - ros-noetic-xacro
      run:
        - python {{ python }}
        - ros-noetic-actionlib
        - ros-noetic-angles
        - ros-noetic-control-msgs
        - ros-noetic-control-toolbox
        - ros-noetic-controller-interface
        - ros-noetic-hardware-interface
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-roscpp
        - ros-noetic-trajectory-msgs
        - ros-noetic-urdf
    script: bld_catkin.bat
  - name: ros-noetic-kdl-parser
    version: 1.14.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - orocos-kdl
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-cmake-modules
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-rostest
        - ros-noetic-urdf
        - tinyxml
        - tinyxml2
        - urdfdom_headers
      run:
        - orocos-kdl
        - python {{ python }}
        - ros-noetic-rosconsole
        - ros-noetic-urdf
        - tinyxml
        - tinyxml2
        - urdfdom_headers
    script: bld_catkin.bat
  - name: ros-noetic-position-controllers
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-controller-interface
        - ros-noetic-forward-command-controller
        - ros-noetic-pluginlib
      run:
        - python {{ python }}
        - ros-noetic-controller-interface
        - ros-noetic-forward-command-controller
        - ros-noetic-pluginlib
    script: bld_catkin.bat
  - name: ros-noetic-robot-state-publisher
    version: 1.15.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - eigen
        - orocos-kdl
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-kdl-parser
        - ros-noetic-rosbag
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-rostest
        - ros-noetic-rostime
        - ros-noetic-sensor-msgs
        - ros-noetic-tf
        - ros-noetic-tf2-kdl
        - ros-noetic-tf2-ros
        - urdfdom_headers
      run:
        - orocos-kdl
        - python {{ python }}
        - ros-noetic-kdl-parser
        - ros-noetic-rosconsole
        - ros-noetic-roscpp
        - ros-noetic-rostime
        - ros-noetic-sensor-msgs
        - ros-noetic-tf
        - ros-noetic-tf2-kdl
        - ros-noetic-tf2-ros
    script: bld_catkin.bat
  - name: ros-noetic-ros-controllers
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-catkin
      run:
        - python {{ python }}
        - ros-noetic-ackermann-steering-controller
        - ros-noetic-diff-drive-controller
        - ros-noetic-effort-controllers
        - ros-noetic-force-torque-sensor-controller
        - ros-noetic-forward-command-controller
        - ros-noetic-gripper-action-controller
        - ros-noetic-imu-sensor-controller
        - ros-noetic-joint-state-controller
        - ros-noetic-joint-trajectory-controller
        - ros-noetic-position-controllers
        - ros-noetic-velocity-controllers
    script: bld_catkin.bat
  - name: ros-noetic-velocity-controllers
    version: 0.16.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - python {{ python }}
        - ros-noetic-angles
        - ros-noetic-catkin
        - ros-noetic-control-msgs
        - ros-noetic-control-toolbox
        - ros-noetic-controller-interface
        - ros-noetic-forward-command-controller
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-urdf
      run:
        - python {{ python }}
        - ros-noetic-angles
        - ros-noetic-control-msgs
        - ros-noetic-control-toolbox
        - ros-noetic-controller-interface
        - ros-noetic-forward-command-controller
        - ros-noetic-pluginlib
        - ros-noetic-realtime-tools
        - ros-noetic-urdf
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge
