package:
  name: ros
  version: 2020.04.26

source:
  - git_url: https://github.com/ros-gbp/geometry2-release.git
    git_rev: release/noetic/tf2/0.7.0-1
    folder: ros-noetic-tf2/src/work
    patches:
      - patch/ros-noetic-tf2.patch

build:
  number: 1
  skip: true  # [not win64]

outputs:
  - name: ros-noetic-tf2
    version: 0.7.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - console_bridge
        - python {{ python }}
        - ros-noetic-catkin
        - ros-noetic-geometry-msgs
        - ros-noetic-rostime
        - ros-noetic-tf2-msgs
      run:
        - console_bridge
        - python {{ python }}
        - ros-noetic-geometry-msgs
        - ros-noetic-rostime
        - ros-noetic-tf2-msgs
    script: bld_catkin.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge
